<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Pages\Tooltip.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Pages\mhc4bdce.yty~" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="BlazorInputFileExtended" Version="2.4.22" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.3" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.3" PrivateAssets="all" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.3" />
	  <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.3" />
	  <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\LexiconLMSBlazor.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Pages\Toasts\ToastDeleteModule.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Pages\Toasts\ToastTemplate.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

</Project>
